// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace QAWorks.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class QAWorksTestsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "QAW_MainMenu.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "QAWorksTests", "\tPerform some basic tests on the QAWorks website.\r\n\tAs a user of the QAWorks webs" +
                    "ite", ProgrammingLanguage.CSharp, new string[] {
                        "FunctionalTests"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "QAWorksTests")))
            {
                QAWorks.Features.QAWorksTestsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user I want a contact us page so that I can find out more about QAWorks" +
            " exciting services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        public virtual void AsAnEndUserIWantAContactUsPageSoThatICanFindOutMoreAboutQAWorksExcitingServices()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an end user I want a contact us page so that I can find out more about QAWorks" +
                    " exciting services", ((string[])(null)));
#line 6
 this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am on the QAWorks web site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("I click on the \"ContactUs\" main menu item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("I land on the \"ContactUs\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "email",
                        "message"});
            table1.AddRow(new string[] {
                        "j.Bloggs",
                        "j.Bloggs@qaworks.com",
                        "please contact me I want to find out more"});
#line 10
 testRunner.And("I should be able to contact QAWorks with the following information", ((string)(null)), table1, "And ");
#line 13
 testRunner.And("the \"ContactUs\" page is redisplayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData(string name_Email_Message, string errortext, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an end user when I am on the Contact Us page I want to be told about incorrect" +
                    " or missing data", exampleTags);
#line 15
 this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I am on the QAWorks web site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("I click on the \"ContactUs\" main menu item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("I land on the \"ContactUs\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.When(string.Format("I populate the ContactUs form with data {0}", name_Email_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then(string.Format("I should see error text {0}", errortext), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user when I am on the Contact Us page I want to be told about incorrect" +
            " or missing data: \" ~j.Bloggs@qaworks.com~please contact me I want to find out m" +
            "ore\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\" ~j.Bloggs@qaworks.com~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:name_email_message", "\" ~j.Bloggs@qaworks.com~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errortext", "Your name is required")]
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData_J_BloggsQaworks_ComPleaseContactMeIWantToFindOutMore()
        {
            this.AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData("\" ~j.Bloggs@qaworks.com~please contact me I want to find out more\"", "Your name is required", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user when I am on the Contact Us page I want to be told about incorrect" +
            " or missing data: \"j.Bloggs~ ~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"j.Bloggs~ ~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:name_email_message", "\"j.Bloggs~ ~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errortext", "An Email address is required")]
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData_J_BloggsPleaseContactMeIWantToFindOutMore()
        {
            this.AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData("\"j.Bloggs~ ~please contact me I want to find out more\"", "An Email address is required", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user when I am on the Contact Us page I want to be told about incorrect" +
            " or missing data: \"j.Bloggs~j.Bloggs@qaworks.com~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"j.Bloggs~j.Bloggs@qaworks.com~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:name_email_message", "\"j.Bloggs~j.Bloggs@qaworks.com~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errortext", "Please type your message")]
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData_J_BloggsJ_BloggsQaworks_Com()
        {
            this.AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData("\"j.Bloggs~j.Bloggs@qaworks.com~ \"", "Please type your message", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user when I am on the Contact Us page I want to be told about incorrect" +
            " or missing data: \" ~ ~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\" ~ ~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:name_email_message", "\" ~ ~ \"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errortext", "Your name is required~An Email address is required~Please type your message")]
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData_()
        {
            this.AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData("\" ~ ~ \"", "Your name is required~An Email address is required~Please type your message", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an end user when I am on the Contact Us page I want to be told about incorrect" +
            " or missing data: \"j.Bloggs~j.Bloggs~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "QAWorksTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FunctionalTests")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"j.Bloggs~j.Bloggs~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:name_email_message", "\"j.Bloggs~j.Bloggs~please contact me I want to find out more\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errortext", "Invalid Email Address")]
        public virtual void AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData_J_BloggsJ_BloggsPleaseContactMeIWantToFindOutMore()
        {
            this.AsAnEndUserWhenIAmOnTheContactUsPageIWantToBeToldAboutIncorrectOrMissingData("\"j.Bloggs~j.Bloggs~please contact me I want to find out more\"", "Invalid Email Address", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
